### ISSUE TITLE
Install and configure an operating system of the GNU/Linux family

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-Omelchenkoff#2]
Overview
========

In order to have a superior development environment, you need to set up and configure appropriate software yourself. You also need to know how to configure things, where they are in your system and how to survive in that scary black thing with white letters in it — The Terminal.

![](https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero.png)

Let's start by setting up an operating system of the [GNU/Linux OS family](https://www.quora.com/Is-Linux-an-operating-system-or-a-kernel/answer/Hary-Irfantri) (that is based on [a kernel called Linux](https://www.quora.com/Is-Linux-an-operating-system-or-a-kernel/answer/Hary-Irfantri)).
Now, you have two options: use [Fedora] **(recommended)** or some flavor of Ubuntu (like XUbuntu, frequently used by beginners).
It's best to install it directly on your hardware (as a dual-boot, if needed) but you can also try it out in a VM (like [VirtualBox]).
You also choose to stay on macOS if absolutely necessary but you'll still have to learn your way around terminal-based approaches.

The objective of this task is to get familiar with command-line tools and learn to set up software without using any of the GUI software.

Fedora
------
* [x] Install [Fedora](https://getfedora.org/en/workstation/download/)
* [x] Learn about DNF/YUM/RPM. [Here](https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/package-management/DNF/) and [there](https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/RPM/). Also: https://fedoramagazine.org/rpm-packages-explained/.
* [x] [optionally] Add RPM Fusion to your system: https://rpmfusion.org/
* [x] Install [Kitty terminal emulator](https://copr.fedorainfracloud.org/coprs/gagbo/kitty-latest/)
* [x] [Install Google Chrome](https://www.if-not-true-then-false.com/2010/install-google-chrome-with-yum-on-fedora-red-hat-rhel/). No GUI-based install, please.
* [x] Install [Git](https://git-scm.com/download/linux)
* [x] Install VS Code using [this instruction](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions), **but** without downloading `*.rpm` file from browser.

Ubuntu
------
* [ ] Install [XUbuntu](https://xubuntu.org/)
* [ ] Learn about APT. [Here](https://help.ubuntu.com/lts/serverguide/apt.html.en) and [there](https://help.ubuntu.com/community/AptGet/Howto)
* [ ] Install [Kitty terminal emulator](https://sw.kovidgoyal.net/kitty/binary.html)
* [ ] [Install Google Chrome](https://www.linuxbabe.com/ubuntu/install-google-chrome-ubuntu-18-04-lts) but scroll to the section `"Install Google Chrome on Ubuntu 18.04 LTS from the Command Line"` and use it. No GUI-based install, please.
* [ ] Install [Git from PPA](https://git-scm.com/download/linux)
* [ ] Install VS Code using [this instruction](https://code.visualstudio.com/docs/setup/linux#_installation), **but** without downloading `*.deb` file so find the line `"The repository and key can also be installed manually with the following script:"` and go from there

[Fedora]: https://getfedora.org/
[VirtualBox]: https://www.virtualbox.org/

**Comment by Omelchenkoff** [comment]
done

**Comment by webknjaz** [comment]
So from now on, use Kitty as a terminal emulator.
You may want to play with configuring it, like the font setting ( https://github.com/webknjaz/ansible-gentoo-laptop/blob/a71c285ad9faf9cffb8d5634da0e4ba27cac50b1/roles/gentoo-userspace/templates/kitty.conf#L13), fallback fonts (https://github.com/webknjaz/ansible-gentoo-laptop/blob/a71c285ad9faf9cffb8d5634da0e4ba27cac50b1/roles/gentoo-userspace/templates/kitty.conf#L45), font size (https://github.com/webknjaz/ansible-gentoo-laptop/blob/a71c285ad9faf9cffb8d5634da0e4ba27cac50b1/roles/gentoo-userspace/templates/kitty.conf#L30) and so on.

If you feel like you know how to deal with installing software on Fedora, close this issue.

Also, please write down what option you chose: is it a VM or a bare metal install?

:point_down: The button is here

**Comment by Omelchenkoff** [comment]
I uninstalled Windows and installed Fedora 31 Workstation on my Lenovo.
gnome v.3.34.1
